apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
  namespace: cl
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/k8s-data/
    type: DirectoryOrCreate