apiVersion: v1
kind: Secret
metadata:
  name: secret-credentials
  namespace: cl

#WARNING: You should not place the real username and password in the version control repository
#          or anywhere else in plain text.
#         The following is just a placeholder!
stringData:
  database-admin-username: postgres
  database-admin-password: postgres
  database-app-username: crowd-library
  database-app-password: crowd-library


