apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  namespace: cl
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/k8s-data/postgres-data
    type: DirectoryOrCreate