apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-deploy
  namespace: cl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubectl-role
  namespace: cl
rules:
  - verbs: ["*"]
    resources: ["*"]
    apiGroups: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-role-binding
  namespace: cl
subjects:
  - kind: ServiceAccount
    name: auto-deploy
    namespace: cl
roleRef:
  kind: Role
  name: kubectl-role
  apiGroup: rbac.authorization.k8s.io
